[package]
name = "fakepay-provider"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
async-trait = "0.1"
log = "0.4"
wasmcloud-interface-factorial = "0.3"
wasmbus-rpc = "0.6"
wasmcloud-examples-payments = { path = "../payments/rust"}

# test dependencies
[dev-dependencies]
wasmcloud-test-util = "0.1"
tokio = { version = "1.0", features = [ "full" ] }

[[bin]]
name = "fakepay_provider"
path = "src/main.rs"
